-- Examples

DROP TABLE IF EXISTS ELECTRODOMESTICOS;
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE ELECTRODOMESTICOS (
    ID INTEGER IDENTITY PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL,
    POTENCIA INTEGER NOT NULL,
    TIEMPO_FUNCIONAMIENTO INTEGER NOT NULL
);

CREATE TABLE CLIENTES (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    PAIS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);